networks:
  monitoring:
    driver: bridge

services:
  grafana:
    image: grafana/grafana:9.0.5
    env_file:
      - .grafana
    container_name: mk_grafana
    restart: always
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus
  
  prometheus:
    image: prom/prometheus
    env_file:
      - .prometheus
    container_name: mk_prometheus
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus
      - ./prometheus/data/:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring

  snmp_exporter:
    image: prom/snmp-exporter
    container_name: mk_snmp_exporter
    restart: always
    volumes:
      - ./snmp/:/etc/snmp_exporter/
    ports:
      - "9116:9116"
    networks:
      - monitoring
    depends_on:
      - prometheus
